// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWY8_RkA5anpRNYy-EJjlUuYImFdfD_d4',
    appId: '1:297981604603:web:be9757d8430227ac37365e',
    messagingSenderId: '297981604603',
    projectId: 'sign-in-25b87',
    authDomain: 'sign-in-25b87.firebaseapp.com',
    storageBucket: 'sign-in-25b87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKEbV93IcesoeqgiIBGZdRRAsco6ZZ3A',
    appId: '1:297981604603:android:14c363d1d247138237365e',
    messagingSenderId: '297981604603',
    projectId: 'sign-in-25b87',
    storageBucket: 'sign-in-25b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZoYe3xh2z-ccHlNHjqCE7wlhwDoNLW8',
    appId: '1:297981604603:ios:0216f3f6e90ce63937365e',
    messagingSenderId: '297981604603',
    projectId: 'sign-in-25b87',
    storageBucket: 'sign-in-25b87.firebasestorage.app',
    iosBundleId: 'com.example.isupplyHackathonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbZoYe3xh2z-ccHlNHjqCE7wlhwDoNLW8',
    appId: '1:297981604603:ios:0216f3f6e90ce63937365e',
    messagingSenderId: '297981604603',
    projectId: 'sign-in-25b87',
    storageBucket: 'sign-in-25b87.firebasestorage.app',
    iosBundleId: 'com.example.isupplyHackathonProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWY8_RkA5anpRNYy-EJjlUuYImFdfD_d4',
    appId: '1:297981604603:web:6e2dea659ba9645337365e',
    messagingSenderId: '297981604603',
    projectId: 'sign-in-25b87',
    authDomain: 'sign-in-25b87.firebaseapp.com',
    storageBucket: 'sign-in-25b87.firebasestorage.app',
  );
}
